ALTER TABLE shipments ADD COLUMN IF NOT EXISTS origin_lat NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS origin_lng NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS destination_lat NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS destination_lng NUMERIC;
