ALTER TABLE shipments ADD COLUMN IF NOT EXISTS current_lat NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS current_lng NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS current_speed_mph NUMERIC;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS last_location_update TIMESTAMPTZ;
